services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
    ports:
      - 5433:5432


volumes:
  postgres-data:
    driver: local
