CREATE TABLE documents (
    id SERIAL PRIMARY KEY,
    content TEXT,
    document_tsvector TSVECTOR
);

INSERT INTO documents (content, document_tsvector)
VALUES
    ('De heer de Vries is behandeld voor rugpijn. Hij heeft fysiotherapie gevolgd om de spierkracht in zijn rug te versterken en herhaling van klachten te voorkomen. Als onderdeel van de behandeling is hem Brufen (ibuprofen) 400 mg voorgeschreven, driemaal daags na de maaltijd, om de pijn en ontsteking te verminderen. Hij is geïnstrueerd deze medicatie niet langer dan nodig te gebruiken en te stoppen zodra de pijn afneemt.', 
    to_tsvector('dutch', 'De heer de Vries is behandeld voor rugpijn. Hij heeft fysiotherapie gevolgd om de spierkracht in zijn rug te versterken en herhaling van klachten te voorkomen. Als onderdeel van de behandeling is hem Brufen (ibuprofen) 400 mg voorgeschreven, driemaal daags na de maaltijd, om de pijn en ontsteking te verminderen. Hij is geïnstrueerd deze medicatie niet langer dan nodig te gebruiken en te stoppen zodra de pijn afneemt.')),

    ('De heer de Vries heeft hoofdpijnklachten ervaren, die nu verminderd zijn. Hij is geadviseerd om stress en mogelijke triggers zoals fel licht te vermijden. Voor de pijnstilling is hem Sumatriptan (Imigran) 50 mg voorgeschreven, te nemen bij de eerste tekenen van een migraineaanval. Hij is geïnstrueerd deze medicatie alleen te gebruiken als het echt nodig is en de gebruiksinstructies nauwkeurig te volgen.', 
    to_tsvector('dutch', 'De heer de Vries heeft hoofdpijnklachten ervaren, die nu verminderd zijn. Hij is geadviseerd om stress en mogelijke triggers zoals fel licht te vermijden. Voor de pijnstilling is hem Sumatriptan (Imigran) 50 mg voorgeschreven, te nemen bij de eerste tekenen van een migraineaanval. Hij is geïnstrueerd deze medicatie alleen te gebruiken als het echt nodig is en de gebruiksinstructies nauwkeurig te volgen.')),

    ('De heer de Vries had last van buikpijn, die is verminderd na het aanpassen van zijn dieet en levensstijl. Hij is geadviseerd een gezond voedingspatroon te blijven volgen en regelmatig te eten. Voor de pijn is hem Buscopan (butylscopolamine) 10 mg voorgeschreven, driemaal daags indien nodig. Dit zal helpen bij het verlichten van de krampen.', 
    to_tsvector('dutch', 'De heer de Vries had last van buikpijn, die is verminderd na het aanpassen van zijn dieet en levensstijl. Hij is geadviseerd een gezond voedingspatroon te blijven volgen en regelmatig te eten. Voor de pijn is hem Buscopan (butylscopolamine) 10 mg voorgeschreven, driemaal daags indien nodig. Dit zal helpen bij het verlichten van de krampen.')),

    ('De heer de Vries is behandeld voor duizeligheid, die nu onder controle is. Hij is geadviseerd goed gehydrateerd te blijven en plotselinge bewegingen te vermijden om duizeligheid te voorkomen. Op dit moment is er geen noodzaak voor medicatie, maar als de symptomen terugkeren, wordt verder onderzoek aanbevolen.', 
    to_tsvector('dutch', 'De heer de Vries is behandeld voor duizeligheid, die nu onder controle is. Hij is geadviseerd goed gehydrateerd te blijven en plotselinge bewegingen te vermijden om duizeligheid te voorkomen. Op dit moment is er geen noodzaak voor medicatie, maar als de symptomen terugkeren, wordt verder onderzoek aanbevolen.')),

    ('De heer de Vries heeft kniepijn ervaren, die nu onder controle is. Hij is geadviseerd de voorgeschreven oefeningen te blijven doen en overbelasting van zijn knie te vermijden. Voor de pijn is hem Diclofenac (Voltaren) 50 mg voorgeschreven, tweemaal daags na de maaltijd. Hij is geïnstrueerd deze medicatie alleen indien nodig te gebruiken en te stoppen zodra de pijn vermindert.', 
    to_tsvector('dutch', 'De heer de Vries heeft kniepijn ervaren, die nu onder controle is. Hij is geadviseerd de voorgeschreven oefeningen te blijven doen en overbelasting van zijn knie te vermijden. Voor de pijn is hem Diclofenac (Voltaren) 50 mg voorgeschreven, tweemaal daags na de maaltijd. Hij is geïnstrueerd deze medicatie alleen indien nodig te gebruiken en te stoppen zodra de pijn vermindert.')),
    
    ('Mevrouw Almeda is behandeld voor schouderpijn. Ze heeft fysiotherapie gevolgd om de mobiliteit van haar schouder te verbeteren en verdere klachten te voorkomen. Als onderdeel van de behandeling is haar Naproxen (Aleve) 500 mg voorgeschreven, tweemaal daags na de maaltijd, om de pijn en ontsteking te verminderen. Ze is geïnstrueerd deze medicatie niet langer dan nodig te gebruiken en te stoppen zodra de pijn afneemt.', 
    to_tsvector('dutch', 'Mevrouw Almeda is behandeld voor schouderpijn. Ze heeft fysiotherapie gevolgd om de mobiliteit van haar schouder te verbeteren en verdere klachten te voorkomen. Als onderdeel van de behandeling is haar Naproxen (Aleve) 500 mg voorgeschreven, tweemaal daags na de maaltijd, om de pijn en ontsteking te verminderen. Ze is geïnstrueerd deze medicatie niet langer dan nodig te gebruiken en te stoppen zodra de pijn afneemt.')),

    ('Mevrouw Almeda heeft last gehad van sinusitis, die nu verminderd is. Ze is geadviseerd om voldoende te rusten en stoominhalaties te doen. Voor de pijn en ontsteking is haar Amoxicilline 500 mg voorgeschreven, driemaal daags voor een periode van 10 dagen. Ze is geïnstrueerd de volledige kuur af te maken, zelfs als de symptomen verbeteren.', 
    to_tsvector('dutch', 'Mevrouw Almeda heeft last gehad van sinusitis, die nu verminderd is. Ze is geadviseerd om voldoende te rusten en stoominhalaties te doen. Voor de pijn en ontsteking is haar Amoxicilline 500 mg voorgeschreven, driemaal daags voor een periode van 10 dagen. Ze is geïnstrueerd de volledige kuur af te maken, zelfs als de symptomen verbeteren.')),

    ('Mevrouw Almeda had last van een verstuikte enkel, die nu genezen is. Ze is geadviseerd om haar enkel te blijven ondersteunen met een brace tijdens inspanning en om geleidelijk aan weer te beginnen met lichte oefeningen. Voor de pijn is haar Paracetamol 500 mg voorgeschreven, maximaal viermaal daags indien nodig.', 
    to_tsvector('dutch', 'Mevrouw Almeda had last van een verstuikte enkel, die nu genezen is. Ze is geadviseerd om haar enkel te blijven ondersteunen met een brace tijdens inspanning en om geleidelijk aan weer te beginnen met lichte oefeningen. Voor de pijn is haar Paracetamol 500 mg voorgeschreven, maximaal viermaal daags indien nodig.')),

    ('Mevrouw Almeda is behandeld voor slapeloosheid. Ze is geadviseerd om een regelmatig slaappatroon aan te houden en cafeïne en zware maaltijden voor het slapen te vermijden. Er is op dit moment geen noodzaak voor medicatie, maar als de symptomen aanhouden, wordt verdere evaluatie aanbevolen.', 
    to_tsvector('dutch', 'Mevrouw Almeda is behandeld voor slapeloosheid. Ze is geadviseerd om een regelmatig slaappatroon aan te houden en cafeïne en zware maaltijden voor het slapen te vermijden. Er is op dit moment geen noodzaak voor medicatie, maar als de symptomen aanhouden, wordt verdere evaluatie aanbevolen.')),

    ('Mevrouw Almeda heeft last gehad van een tenniselleboog, die nu onder controle is. Ze is geadviseerd om de arm voldoende rust te geven en rekoefeningen te doen. Voor de pijn is haar Ibuprofen gel 5% voorgeschreven, tweemaal daags op de pijnlijke plek aanbrengen.', 
    to_tsvector('dutch', 'Mevrouw Almeda heeft last gehad van een tenniselleboog, die nu onder controle is. Ze is geadviseerd om de arm voldoende rust te geven en rekoefeningen te doen. Voor de pijn is haar Ibuprofen gel 5% voorgeschreven, tweemaal daags op de pijnlijke plek aanbrengen.')),

    ('Tak is behandeld voor oorontsteking. Hij heeft antibiotica gekregen om de infectie te bestrijden en paracetamol om de pijn te verlichten. Amoxicilline 250 mg, driemaal daags gedurende 7 dagen, is voorgeschreven. Paracetamol 125 mg, maximaal viermaal daags indien nodig voor pijn.', 
    to_tsvector('dutch', 'Tak is behandeld voor oorontsteking. Hij heeft antibiotica gekregen om de infectie te bestrijden en paracetamol om de pijn te verlichten. Amoxicilline 250 mg, driemaal daags gedurende 7 dagen, is voorgeschreven. Paracetamol 125 mg, maximaal viermaal daags indien nodig voor pijn.')),

    ('Tak had last van keelontsteking. Hij heeft rust en warme dranken voorgeschreven gekregen om de irritatie te verlichten. Voor de pijn is ibuprofen 100 mg, driemaal daags indien nodig, voorgeschreven. Tak is geïnstrueerd om veel te drinken en harde of scherpe voedingsmiddelen te vermijden.', 
    to_tsvector('dutch', 'Tak had last van keelontsteking. Hij heeft rust en warme dranken voorgeschreven gekregen om de irritatie te verlichten. Voor de pijn is ibuprofen 100 mg, driemaal daags indien nodig, voorgeschreven. Tak is geïnstrueerd om veel te drinken en harde of scherpe voedingsmiddelen te vermijden.')),

    ('Tak heeft last gehad van waterpokken. Hij kreeg een antihistaminicum voorgeschreven om de jeuk te verminderen en werd geadviseerd om zijn nagels kort te houden om krabben te voorkomen. Voor de jeuk is cetirizine 5 mg, eenmaal daags, voorgeschreven. Daarnaast is calamine lotion aanbevolen om op de huid aan te brengen.', 
    to_tsvector('dutch', 'Tak heeft last gehad van waterpokken. Hij kreeg een antihistaminicum voorgeschreven om de jeuk te verminderen en werd geadviseerd om zijn nagels kort te houden om krabben te voorkomen. Voor de jeuk is cetirizine 5 mg, eenmaal daags, voorgeschreven. Daarnaast is calamine lotion aanbevolen om op de huid aan te brengen.')),

    ('Tak is behandeld voor astma. Hij heeft een inhalator gekregen voor noodsituaties en een preventieve inhalator voor dagelijks gebruik. Voor acute symptomen is salbutamol (Ventolin) voorgeschreven, 100 microgram per inhalatie, maximaal viermaal daags indien nodig. Voor dagelijkse preventie is beclometason (Qvar) voorgeschreven, 50 microgram per inhalatie, tweemaal daags.', 
    to_tsvector('dutch', 'Tak is behandeld voor astma. Hij heeft een inhalator gekregen voor noodsituaties en een preventieve inhalator voor dagelijks gebruik. Voor acute symptomen is salbutamol (Ventolin) voorgeschreven, 100 microgram per inhalatie, maximaal viermaal daags indien nodig. Voor dagelijkse preventie is beclometason (Qvar) voorgeschreven, 50 microgram per inhalatie, tweemaal daags.')),

    ('Tak had een verkoudheid. Hij werd geadviseerd om veel te rusten, voldoende te drinken en eventueel een zoutoplossing te gebruiken om de neus te spoelen. Er is geen medicatie voorgeschreven aangezien de symptomen mild waren en binnen enkele dagen zouden moeten verbeteren.', 
    to_tsvector('dutch', 'Tak had een verkoudheid. Hij werd geadviseerd om veel te rusten, voldoende te drinken en eventueel een zoutoplossing te gebruiken om de neus te spoelen. Er is geen medicatie voorgeschreven aangezien de symptomen mild waren en binnen enkele dagen zouden moeten verbeteren.'));

